-- Criação da tabela para armazenar avaliações de funcionários
CREATE TABLE IF NOT EXISTS FUN_AVALIACOES_FEEDBACK (
    AVA_ID INT PRIMARY KEY AUTO_INCREMENT,
    AVA_FUNCIONARIO_ID INT NOT NULL,
    AVA_AVALIADO_POR VARCHAR(100) NOT NULL,
    AVA_DATA_FEEDBACK DATE NOT NULL,
    AVA_CARGO VARCHAR(100) NOT NULL,
    
    -- Avaliações de Desempenho (escala 1-5)
    AVA_QUALIDADE_TRABALHO TINYINT CHECK (AVA_QUALIDADE_TRABALHO BETWEEN 1 AND 5),
    AVA_PRODUTIVIDADE TINYINT CHECK (AVA_PRODUTIVIDADE BETWEEN 1 AND 5),
    AVA_COLABORACAO TINYINT CHECK (AVA_COLABORACAO BETWEEN 1 AND 5),
    AVA_COMUNICACAO TINYINT CHECK (AVA_COMUNICACAO BETWEEN 1 AND 5),
    AVA_COMPROMETIMENTO TINYINT CHECK (AVA_COMPROMETIMENTO BETWEEN 1 AND 5),
    
    -- Feedback Qualitativo
    AVA_PONTOS_FORTES TEXT,
    AVA_PONTOS_MELHORIA TEXT,
    AVA_SUGESTAO_EVOLUCAO TEXT,
    
    -- Campos de Auditoria
    AVA_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AVA_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    AVA_CREATED_BY INT,
    
    -- Chaves estrangeiras
    FOREIGN KEY (AVA_FUNCIONARIO_ID) REFERENCES FUN_FUNCIONARIO(FUN_ID),
    FOREIGN KEY (AVA_CREATED_BY) REFERENCES usu_usuario(USU_ID)
);

-- Criar índices para melhor performance
CREATE INDEX idx_funcionario_avaliacao ON FUN_AVALIACOES_FEEDBACK(AVA_FUNCIONARIO_ID);
CREATE INDEX idx_data_avaliacao ON FUN_AVALIACOES_FEEDBACK(AVA_DATA_FEEDBACK);
CREATE INDEX idx_avaliado_por ON FUN_AVALIACOES_FEEDBACK(AVA_AVALIADO_POR);

-- Comentários da tabela
ALTER TABLE FUN_AVALIACOES_FEEDBACK COMMENT = 'Tabela para armazenar avaliações de desempenho dos funcionários';